### ISSUE TITLE
Forced asking for location permission

### ISSUE THREAD

**Issue by MateuszMlodawski** [airbnb/AirMapView#110]
Hey,

looks like the library asks for a location permission on behalf of us. What I'd like to achieve is to ask for this permission on my own.

From what I can see `checkLocationPermissions()` checks if permission is granted and asks for it if not. This method is used only from `setMyLocationEnabled()` method. This would be acceptable if, as a workaround, I could pass `false` to it and avoid asking. Unfortunately in `NativeGoogleMapFragment` `init()` method there's a `setMyLocationEnabled(true)` call which forces asking for permission.

Is this correct or am I missing something?

As for me, the ideal solution would be to completely remove asking for this permission from AirMapView and leave it to developer's decision. Another, that would probably work for most of people, would be to remove `setMyLocationEnabled(true)` from mentioned `init()` method.

What do you think?

**Comment by MateuszMlodawski** [comment]
Ok, I see it was merged in #99 but is not released yet. Any plans for releasing it?

**Comment by felipecsl** [comment]
@MateuszMlodawski I'll cut a v1.5 release!

**Comment by felipecsl** [comment]
Released!
