### ISSUE TITLE
I have this error in gradle

### ISSUE THREAD

**Issue by EpsilonOrionis** [airbnb/AirMapView#28]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.amazon.android:amazon-maps-api:2.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/amazon/android/amazon-maps-api/2.0/amazon-maps-api-2.0.pom
         https://jcenter.bintray.com/com/amazon/android/amazon-maps-api/2.0/amazon-maps-api-2.0.aar
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/android/m2repository/com/amazon/android/amazon-maps-api/2.0/amazon-maps-api-2.0.pom
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/android/m2repository/com/amazon/android/amazon-maps-api/2.0/amazon-maps-api-2.0.aar
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/google/m2repository/com/amazon/android/amazon-maps-api/2.0/amazon-maps-api-2.0.pom
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/google/m2repository/com/amazon/android/amazon-maps-api/2.0/amazon-maps-api-2.0.aar
     Required by:
         Link:app:unspecified > com.airbnb.android:airmapview:1.1.2
   > Could not find com.google.android.gms:play-services-maps:7.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/7.0.0/play-services-maps-7.0.0.pom
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/7.0.0/play-services-maps-7.0.0.jar
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/7.0.0/play-services-maps-7.0.0.pom
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/7.0.0/play-services-maps-7.0.0.jar
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-maps/7.0.0/play-services-maps-7.0.0.pom
         file:/C:/Users/Mirko/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-maps/7.0.0/play-services-maps-7.0.0.jar
     Required by:
         Link:app:unspecified > com.airbnb.android:airmapview:1.1.2

**Comment by felipecsl** [comment]
The problem with Amazon maps is that it's currently not on Maven Central, so you basically have to download it yourself and manually add it to your project's dependencies, which is far from ideal.
If you don't want to use Amazon maps you shouldn't have to still get it though. In order to fix this, we're gonna make the Amazon maps dependency optional, so you'll only have to pull it if you want to use. In the meantime we're gonna remove it until this issue is sorted out.

**Comment by petzel** [comment]
@EpsilonOrionis this should be fixed in the latest version. If you're using gradle/maven you can pull the new version which is 1.1.3
