### ISSUE TITLE
getMapAsync

### ISSUE THREAD

**Issue by tier777** [airbnb/AirMapView#33]
Hi, how i can initialize map with async task?

Like:

    .getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(GoogleMap googleMap) {
             
            }
        });

https://developer.android.com/reference/com/google/android/gms/maps/MapFragment.html#getMapAsync(com.google.android.gms.maps.OnMapReadyCallback)

**Comment by nwadams** [comment]
I'll add that functionality. Thanks.

**Comment by nwadams** [comment]
You should use the `OnMapInitializedListener` which behaves like the `getMapAsync`
```
map.setOnMapInitializedListener(this);
map.initialize(getSupportFragmentManager());
```

See line 54 of the MainActivity in the sample. https://github.com/airbnb/AirMapView/blob/master/sample/src/main/java/com/airbnb/airmapview/sample/MainActivity.java#L54
