### ISSUE TITLE
Fail on compile

### ISSUE THREAD

**Issue by ppamorim** [airbnb/AirMapView#40]
This return a error when I try to compile.
The build of gradle works well, but the app, not.

    Error:Execution failed for task ':app:dexDebug'.
    > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'' finished with non-zero exit value 2

**Comment by felipecsl** [comment]
It sounds like something is wrong with your jdk installation.

**Comment by ppamorim** [comment]
@felipecsl It only happens with this library. No way!

**Comment by felipecsl** [comment]
can you run a `./gradlew clean assemble --stacktrace` and paste the full stack/error please?
