### ISSUE TITLE
Blank Map (Web)

### ISSUE THREAD

**Issue by anupsarode** [airbnb/AirMapView#42]
Hello,

I tried the code below in the Emulator as well as on real device. Both the devices doesn't have Google Play Services installed so a web based version of map is shown. But for some reason, the map is always blank with just blue color. Attached is the screenshot. Am I missing something?

![screen shot 2015-06-09 at 4 39 02 pm](https://cloud.githubusercontent.com/assets/2538927/8056485/4a8db50c-0ec6-11e5-9683-9f96d01e00ae.png)

MainActivity.java
-----------------------
mapViewBuilder = new DefaultAirMapViewBuilder(this);
map = (AirMapView) findViewById(R.id.map_view);
map.setOnMapInitializedListener(this);
map.initialize(getSupportFragmentManager());

Layout
----------
<com.airbnb.android.airmapview.AirMapView
        android:id="@+id/map_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

**Comment by felipecsl** [comment]
this is probably because you forgot to set the map center. what you're looking at is probably water in the middle of nowhere :smile: 
look at MainActivity.java for an example, ultimately you need somethingl ike `map.animateCenterZoom(latLng, zoom);`

**Comment by anupsarode** [comment]
@felipecsl - That did the trick. Thanks!
