### ISSUE TITLE
Clustering markers

### ISSUE THREAD

**Issue by dommerq** [airbnb/AirMapView#48]
What the title says.

**Comment by nwadams** [comment]
The library currently has no clustering support. It would be cool if someone were to add it.

**Comment by dommerq** [comment]
Well you have it on AirBnb right? Aren't you using this AirMapView in the app? Or are you adding some other library on the top of it? (which one)
I'm confused.

**Comment by nwadams** [comment]
Our current version of the android app doesn't have clustering of markers. We used to have it in a super old version, but it was janky.
