### ISSUE TITLE
Support for changing map type (e.g. Roadmap, Satellite, Hybrid)

### ISSUE THREAD

**Issue by paulotubbert** [airbnb/AirMapView#51]
Hi, 

Are there plans to add support for switching between map types to the AirMapInterface?

The native GoogleMap object offers the setMapType(int), it would be quite useful if a similar method was exposed via the AirMapInterface. In particular it would be useful to be able to switch between "roadmap" and "satellite" programmatically. As it stands there doesn't appear to be any way to change the default map type, which is Roadmap.

For reference, the map types available via the Google Maps Javascript API are described here:
https://developers.google.com/maps/documentation/javascript/maptypes

**Comment by felipecsl** [comment]
sounds like this would be very useful. I'll tackle it
