### ISSUE TITLE
Marker positions are incorrect in web map when device language is changed

### ISSUE THREAD

**Issue by geofffalk** [airbnb/AirMapView#62]
With the sample app installed on a UK based device, Nexus 6 running Lollipop

1. Change device language to Spanish / German etc
2. Select 'Use Google Web Map' or 'Use MapBox Map'
3. RESULT: the markers are incorrectly placed in a horizontal line across globe

If you change the language to certain Asian ones - Chinese, Thai for example, the markers are correctly placed.

**Comment by geofffalk** [comment]
Found fix.
The issue is that the String.format function is translating the commas in the url strings, resulting in corrupted javascript method calls.
To fix the issue, the locale needs to be explicitly set to US in each String.format e.g.
``String.format(Locale.US, "javascript:setMarkerIcon('%1$s', %2$d, %3$d);", markerPath, markerWidth, markerHeight)``

**Comment by geofffalk** [comment]
I see the issue is replicable on the live AirBnB application too.

**Comment by felipecsl** [comment]
thanks @geofffalk

**Comment by petzel** [comment]
@geofffalk thank you for reporting and for the fix!
