### ISSUE TITLE
NativeGoogleMapFragment: Setting location enabled and denying permissions leads to inconsistent state

### ISSUE THREAD

**Issue by WhosPablo** [airbnb/AirMapView#92]
https://github.com/airbnb/AirMapView/blob/master/library/src/main/java/com/airbnb/android/airmapview/NativeGoogleMapFragment.java#L269

Setting location enabled here sets the global variable `myLocationEnabled` to true but if permissions are rejected the `googleMap`'s location is never enabled. Trying to set the location enabled at a later point calling `setMylocationEnabled(true)` will no longer do anything unless you disable the location that was never enabled.

**Comment by felipecsl** [comment]
Fixed via #93
