### ISSUE TITLE
Move map without moving marker

### ISSUE THREAD

**Issue by tranngoclam** [airbnb/AirMapView#94]
Hi all.

I'm using `AirMapView` and have a question that How to move map without moving a marker (indicate my current location on map). My solution is adding an `ImageView` that is `centerInParent` of the map, but when taking the snapshot of the map, it does not have a marker.

Could you all support my question above ?
Thanks

**Comment by nwadams** [comment]
@tranngoclam I don't think you can have a marker that is part of the map but attached to the screen instead of a map location. Perhaps you could "add the marker" and then take a snapshot when needed but keep the `ImageView` on top of the map when the user is moving it around.
