### ISSUE TITLE
NativeGoogleMapFragment#setMyLocationEnabled True By Default

### ISSUE THREAD

**Issue by forrestbice** [airbnb/AirMapView#97]
I'm having trouble understanding why NativeGoogleMapFragment#setMyLocationEnabled is set to true by default here https://github.com/airbnb/AirMapView/blob/70cfd5d32646758c4df868da1fc928b75de88438/library/src/main/java/com/airbnb/android/airmapview/NativeGoogleMapFragment.java#L75

I've been searching for a way to use AirMapView without prompting the user for their location. Is that possible?

**Comment by nwadams** [comment]
fixed by https://github.com/airbnb/AirMapView/issues/99
